### ISSUE TITLE
can't find mpv on mac

### ISSUE THREAD

**Issue by antiboredom** [antiboredom/videogrep-gui#3]
when you hit "preview" mpv cannot be found even if it is installed...

**Comment by jasalt** [comment]
Did not have problems running on Mac 13.1 with mpv installed from homebrew. Tested both Intel and Apple cpu's. Preview launches and seems to work without problems.

Install procedure I used was (with pipenv configured on system):

```
brew install mpv
git clone git@github.com:antiboredom/videogrep-gui.git
cd videogrep-gui
pipenv shell
pipenv install -r
cd src
python -m videogrep_gui
```

**Comment by antiboredom** [comment]
should be fixed now
